# Generated by Django 5.0.1 on 2024-02-03 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=datetime.date.today, default=datetime.date.today),
        ),
    ]
